# import numpy as np

### <span style="color:blue"> 1.Create a 1D array of numbers from 0 to 9.</span>

In [2]:
# nums = np.array(range(10))
nums = np.arange(10)
nums

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### <span style="color:blue">2. Create a 3×3 numpy array of all True’s </span>

In [3]:
result = np.ones((3,3))

result = result>0

print(result)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


### <span style="color:blue"> 3. Given an array as input, print only odd numbers as output </span>



In [4]:
arr = np.array(range(100))
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [5]:
arr[arr%2!=0]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

### <span style="color:blue"> 4. Replace all odd numbers in arr with -2 </span>

In [6]:
arr[arr%2!=0]=-2

In [7]:
arr

array([ 0, -2,  2, -2,  4, -2,  6, -2,  8, -2, 10, -2, 12, -2, 14, -2, 16,
       -2, 18, -2, 20, -2, 22, -2, 24, -2, 26, -2, 28, -2, 30, -2, 32, -2,
       34, -2, 36, -2, 38, -2, 40, -2, 42, -2, 44, -2, 46, -2, 48, -2, 50,
       -2, 52, -2, 54, -2, 56, -2, 58, -2, 60, -2, 62, -2, 64, -2, 66, -2,
       68, -2, 70, -2, 72, -2, 74, -2, 76, -2, 78, -2, 80, -2, 82, -2, 84,
       -2, 86, -2, 88, -2, 90, -2, 92, -2, 94, -2, 96, -2, 98, -2])

### <span style="color:blue"> 5. How to reshape an array? </span>

In [8]:
arr = np.arange(100)
print(f'Shape of array is {arr.shape}')
print()
print(arr)
arr = arr.reshape(2,50)
print()
print(f'Shape of array after reshape is {arr.shape}')
print(arr)

Shape of array is (100,)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]

Shape of array after reshape is (2, 50)
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
  48 49]
 [50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
  74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97
  98 99]]


### <span style="color:blue"> 6.Convert a 1D array to a 2D array with 2 rows </span> 

In [9]:
array_1d = np.array([1,2,3,4,5,6])
array_2d = array_1d.reshape(2,-1)
array_2d

array([[1, 2, 3],
       [4, 5, 6]])

 ### <span style="color:blue"> 7. Given an array  a  = [1,2,3,4,5,6,7,8,9] , create  new array b from a such that b includes all odd numbers and 4 multiples. </span>

In [3]:
a = np.array([1,2,3,4,5,6,7,8,9])
#Index those values which are odd , or which are multiples of 4
# b = a[(a%2!=0)|((a%2==0) & (a%4==0))] #or
b = a[(a%2!=0)&(a%4==0)] #
b

array([], dtype=int32)

 ### <span style="color:blue">8. Given array, check if there are any null values and print them out.</span>

In [6]:
a = np.array([1,2,3,np.nan,4,5,6,7,8,9,np.nan])
# print(a)
a[np.isnan(a)]
# np.isnan(a).any()
np.where(np.isnan(a))

(array([ 3, 10], dtype=int64),)

 ### <span style="color:blue">9.How to replace all missing values with 0 in a numpy array? </span>

In [12]:
a = np.array([1,2,3,np.nan,4,5,6,7,8,9,np.nan])
a[np.isnan(a)]=0
a

array([1., 2., 3., 0., 4., 5., 6., 7., 8., 9., 0.])

 ### <span style="color:blue">10.How to find the count of each unique number in a NumPy array? </span>

In [13]:
import pandas as pd

In [14]:
(unique,counts)=np.unique(a,return_counts=True)
unique,counts

(array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 array([2, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64))

In [15]:
df = pd.DataFrame([unique,counts]).T
df.columns=['value','counts']
df

value  counts
0    0.0     2.0
1    1.0     1.0
2    2.0     1.0
3    3.0     1.0
4    4.0     1.0
5    5.0     1.0
6    6.0     1.0
7    7.0     1.0
8    8.0     1.0
9    9.0     1.0

 ### <span style="color:blue"> 11. How to convert a numeric to a categorical (text) array?</span>

In [16]:
x = np.arange(10)
print(f'Numerical array {x}')

x = x.astype('str')
print(f'Charectar array {x}')

Numerical array [0 1 2 3 4 5 6 7 8 9]
Charectar array ['0' '1' '2' '3' '4' '5' '6' '7' '8' '9']


 ### <span style="color:blue">12. Write a program to print all numbers between 99 and 299 which are either divisible by 5 or 7. Exclude the elements which are divisible by both.  </span> 

In [17]:
a = np.array(range(99,299))
print(f"\nNumbers between 99 and 299 :\n\n{a}")
#Filter the numbers which are either divisible by 5 or 7 but not both
a = a[((a%5==0)&(a%7!=0))|((a%7==0)&(a%5!=0))]
print(f"\nNumbers between 99 and 299 which are either divisible by 5 or 7 but not both :\n\n{a}")


Numbers between 99 and 299 :

[ 99 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116
 117 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134
 135 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152
 153 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170
 171 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188
 189 190 191 192 193 194 195 196 197 198 199 200 201 202 203 204 205 206
 207 208 209 210 211 212 213 214 215 216 217 218 219 220 221 222 223 224
 225 226 227 228 229 230 231 232 233 234 235 236 237 238 239 240 241 242
 243 244 245 246 247 248 249 250 251 252 253 254 255 256 257 258 259 260
 261 262 263 264 265 266 267 268 269 270 271 272 273 274 275 276 277 278
 279 280 281 282 283 284 285 286 287 288 289 290 291 292 293 294 295 296
 297 298]

Numbers between 99 and 299 which are either divisible by 5 or 7 but not both :

[100 110 112 115 119 120 125 126 130 133 135 145 147 150 154 155 160 161
 1

 ### <span style="color:blue"> 13. Write a program to reverse an array and print (Don’t use inbuilt reverse functions)</span>

In [18]:
a = np.array(range(100,199))
print(a)
a[len(a)-1::-1] # stat-index:end-index:step = 99::-1, end-index-blank means all

[100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153
 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171
 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189
 190 191 192 193 194 195 196 197 198]


array([198, 197, 196, 195, 194, 193, 192, 191, 190, 189, 188, 187, 186,
       185, 184, 183, 182, 181, 180, 179, 178, 177, 176, 175, 174, 173,
       172, 171, 170, 169, 168, 167, 166, 165, 164, 163, 162, 161, 160,
       159, 158, 157, 156, 155, 154, 153, 152, 151, 150, 149, 148, 147,
       146, 145, 144, 143, 142, 141, 140, 139, 138, 137, 136, 135, 134,
       133, 132, 131, 130, 129, 128, 127, 126, 125, 124, 123, 122, 121,
       120, 119, 118, 117, 116, 115, 114, 113, 112, 111, 110, 109, 108,
       107, 106, 105, 104, 103, 102, 101, 100])