### <span id="idx">Index</span>

<a href="#idx" target="_self" style="position:fixed">Index</a>

### <a href="#one" target="_self"> 1 </a>N-dimensional Array  (ndarray Object) <br />
<span style="padding-left:50px"><a href="#t1" target="_self">Task1</a><span ><br />
### <a href="#two" target="_self"> 2 </a>Making a ndarray object <br />
<span style="padding-left:30px"><a href="#s1" target="_self">np.zeros</a><span ><br />
    <span style="padding-left:30px"><a href="#s2" target="_self">np.ones</a><span ><br />


N-dimensional Array (ndarray Object)
ndarray is a multidimensional container which can contain only homogeneous items. The shape of such an array is defined by the 'shape' attribute. The data type of the items inside a ndarray is stored in an object known as 'dtype'.

In [2]:
import numpy as np

In [3]:
X = np.array([[1,2,3],[4,5,6]])
X

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
print(f'Shape of X is \t\t: {X.shape}')
print(f'Datatype of X is \t: {X.dtype}')

Shape of X is 		: (2, 3)
Datatype of X is 	: int32


In [17]:
X.dtype

dtype('int64')

<a href="#t1">Task1</a>

Convert the data type of numpy array X from 'int32' to 'int64'. <br />
Replace the value 1 by 5 in numpy array X. <br />
Create a 3-D array with value [1,2,3,4,5,6,7,8,9] such that the shape of the array is represented as (1,3,3). <br />

In [37]:
# Convert the data type of numpy array X from 'int32' to 'int64'.
X = X.astype(np.int64)

print(f'Datatype of X is \t: {X.dtype}')

#Replace the value 1 by 5 in numpy array X
X[0][0]=5
print(f'The array X is : \n {X}')

#Create a 3-D array with value [1,2,3,4,5,6,7,8,9] such that the shape of the array is represented as (1,3,3).
data =  [1,2,3,4,5,6,7,8,9]
array_3d = np.array(data).reshape(1,3,3)
print(f'The array array_3d is : \n {array_3d}')

Datatype of X is 	: int64
The array X is : 
 [[5 2 3]
 [4 5 6]]
The array array_3d is : 
 [[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [21]:
X

array([[5, 2, 3],
       [4, 5, 6]], dtype=int64)

In [26]:
# c
data =  [1,2,3,4,5,6,7,8,9]
type(data)

list

In [31]:
array_3d = np.array(data).reshape(1,3,3)
array_3d

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

<a href="#idx" target="_self" style="position:fixed">Index</a>

### <span id="two"> Making a ndarray object </span> 

<span id="s1" style="font-weight:bold">np.zeros </span><br />
np.zeros :- Creates numpy array of given size and given type initialized with zeros.<br />
<span id="s2" style="font-weight:bold">np.ones </span><br />
np.ones :- Creates numpy array of given size and given type initialized with ones.




In [41]:
x = np.zeros(shape=(2,3),dtype='float')
print(x)

[[0. 0. 0.]
 [0. 0. 0.]]


In [40]:
x

array([[0., 0., 0.],
       [0., 0., 0.]])

<a href="#t2">Task2</a>

Class task <br />
Create a 3 * 3 n-dim array with 3 numbers from np.zeros. <br />
Create a 4 * 2 n-dim array with all ones <br />

In [50]:
zeros = np.zeros((3,3))
print(f'zeros :\n\n {zeros}')

ones = np.ones((4,2))
print(f'\n ones :\n\n {ones}')

zeros :

 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

 ones :

 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
